name: Codacy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Scan:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Checkout
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      
    - name: Codacy Analysis Generation
      uses: codacy/codacy-analysis-cli-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        max-allowed-issues: 500
        output: codacy_analysis.yml

    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: |
          ./codacy_analysis.yml

    - name: Codacy Analysis Report
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: codacy_analysis.xml
