name: Config Docs

on:
  push:
    branches:
      - master

jobs:
  config-docs:
    name: Generate & Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2

      - name: Install
        run: npm ci

      - name: Config Docs
        run: node ./.github/scripts/config-docs.js

      - name: Push
        run: ./.github/scripts/config-docs.sh
